Added Profile & Posts Page
b3fr4nk/PlanUP pull request #36
Opened 2024-02-21 20:36 UTC by el634dev

Issues #12 , #16 , #17

2024-02-22 18:48 UTC, b3fr4nk requested changes
There seems to be a lot of miscommunication I think we need to meet

2024-02-22 18:48 UTC, b3fr4nk commented on templates/browse.html
> +<div class="container container-fluid embed-responsive embed-responsive-16by9 mt-3">
Visually looks really good but none of this uses the backend routes I created. It should get the posts already created and display them. Also you are missing the post details page but that ticket has been moved to finished.

2024-02-22 18:48 UTC, b3fr4nk commented on templates/browse.html
> +        <!--Posts Link-->
Posts leads to the same place as Browse. Should maybe be new post and lead to the new post page

2024-02-22 18:48 UTC, b3fr4nk commented on templates/post.html
> +  <div class="row height d-flex justify-content-center align-items-center">
Identical to the browse page?

2024-02-22 18:48 UTC, b3fr4nk commented on templates/profile_page.html
> +{% extends 'base.html' %}
How do you get here?

2024-02-22 18:48 UTC, b3fr4nk commented on templates/signin.html
> +      <!--Resources-->
Header and footer should probably use a template so we only need to make the change once

2024-02-22 18:48 UTC, b3fr4nk commented on templates/new_post.html
> +        <!--Posts Link-->
No way for the user to get here

2024-02-22 18:48 UTC, b3fr4nk commented on templates/browse.html
> +        <a  href="{{ url_for('pages.browse_page') }}" class="nav-link p-0 text-muted text-decoration-none">
there is a full backend route for this. the get all posts

2024-02-22 18:48 UTC, b3fr4nk commented on templates/signup.html
> +        <a href="{{ url_for('pages.browse_page') }}"  class="nav-link p-0 text-muted text-decoration-none">
again a proper route for this

2024-02-26 19:50 UTC, closed without merging

2024-02-26 19:50 UTC, el634dev commented
Creating new pr